import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, sep } from 'node:path';

const packagePath = resolve('package.json');
const packageJson = JSON.parse(readFileSync(packagePath, 'utf8'));
const expectedPackageName = 'gcsc-construction-ai';

const checkScripts = [
  "check:smartcontractor",
  "check:mobile",
  "check:pwa-qa",
  "check:mobile-install-readiness",
  "check:android-preflight",
  "check:android-wrapper",
  "check:android-toolchain-preflight",
  "check:founder-android-setup",
  "check:android-debug-build-evidence",
  "check:android-emulator-smoke-evidence",
  "check:android-device-smoke-checklist",
  "check:mobile-screenshot-redaction",
  "check:mobile-release-blockers",
  "check:mobile-release-go-no-go",
  "check:mobile-founder-qa-report",
  "check:mobile-local-qa-commands",
  "check:android-qa",
  "check:ios-preflight",
  "check:mobile-release-evidence",
  "check:demo-script",
  "check:controlled-user-test",
  "check:beta-issue-log",
  "check:beta-tester-invite",
  "check:beta-tester-followup",
  "check:beta-feedback-synthesis",
  "check:beta-readiness",
  "check:beta-session",
  "check:beta-session-summary",
  "check:beta-decision-log",
  "check:public-beta-review-packet",
  "check:public-beta-founder-execution-plan",
  "check:beta-triage-rubric",
  "check:beta-issue-lifecycle",
  "check:beta-go-no-go-scorecard",
  "check:beta-evidence-checklist",
  "check:auth",
  "check:auth-rls-plan",
  "check:strict-gates",
  "check:strict-admin-smoke",
  "check:rls-draft",
  "check:strict-rls-live-apply-decision-packet",
  "check:payment-ownership",
  "check:contract-docs",
  "check:smart-contract-implementation-gate",
  "check:smart-contract-authority-model",
  "check:smart-contract-test-fixtures",
  "check:smart-contract-action-register",
  "check:smart-contract-state-machine",
  "check:smart-contract-audit-event-map",
  "check:backend-to-chain-map",
  "check:smart-contract-deployment-blockers",
  "check:smart-contract-rollback-recovery",
  "check:smart-contract-local-replay",
  "check:smart-contract-coding-readiness",
  "check:smart-contract-code-ownership",
  "check:smart-contract-scaffold-handoff",
  "check:smart-contract-scaffold-file-manifest",
  "check:smart-contract-scaffold-review",
  "check:smart-contract-scaffold-merge-record",
  "check:smart-contract-scaffold-release-gate",
  "check:smart-contract-local-implementation-plan",
  "check:smart-contract-local-implementation-kickoff",
  "check:smart-contract-local-implementation-package-index",
  "check:smart-contract-local-package-start-template",
  "check:smart-contract-audit-local-package-start",
  "check:smart-contract-authority-local-package-start",
  "check:smart-contract-escrow-local-package-start",
  "check:smart-contract-loan-local-package-start",
  "check:smart-contract-collateral-local-package-start",
  "check:smart-contract-review-local-package-start",
  "check:smart-contract-audit-serialization-local",
  "check:smart-contract-authority-state-local",
  "check:smart-contract-escrow-state-local",
  "check:smart-contract-loan-state-local",
  "check:smart-contract-repayment-failure-state-local",
  "check:smart-contract-adverse-action-state-local",
  "check:smart-contract-collateral-state-local",
  "check:smart-contract-review-state-local",
  "check:smart-contract-state-helpers-local",
  "check:smart-contract-local-replay-packet",
  "check:smart-contract-helper-index-local",
  "check:smart-contract-local-replay-scenario-bundle",
  "check:smart-contract-local-replay-manifest",
  "check:smart-contract-local-replay-digest",
  "check:smart-contract-local-replay-evidence-bundle",
  "check:smart-contract-local-replay-review-proof",
  "check:smart-contract-local-replay-founder-packet",
  "check:smart-contract-local-replay-live-gate",
  "check:smart-contract-local-replay-approval-checklist",
  "check:smart-contract-local-replay-approval-evidence-template",
  "check:smart-contract-local-replay-approval-handoff-summary",
  "check:smart-contract-local-replay-approval-decision-draft",
  "check:smart-contract-local-replay-approval-decision-intake",
  "check:smart-contract-local-replay-approval-decision-routing",
  "check:smart-contract-local-replay-approval-decision-audit-trail",
  "check:smart-contract-local-replay-approval-decision-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-packet",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-template",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-intake",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-summary",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-action-plan",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-handoff",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-handoff-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-register",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-register-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-template",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-intake",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-summary",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-index",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-index-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-handoff",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-handoff-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-external-record-request",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-external-record-request-closeout",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-external-record-request-closeout-handoff",
  "check:smart-contract-local-replay-approval-decision-external-owner-response-decision-evidence-archive-external-record-request-closeout-handoff-closeout",
  "check:ai-agent-workflows",
  "check:ai-agent-recommendations",
  "check:legal-review",
  "check:gcsc-v1-2-core-architecture-package",
  "check:contract-backed-loan-blueprint",
  "check:whitepaper-sections",
  "check:target-architecture",
  "check:nonstop-hook",
  "check:daily-work-mode-hook",
  "check:founder-evening-command-board",
  "check:automation-health",
  "check:autonomous-status",
  "check:founder-boundaries",
  "check:founder-action-queue",
  "check:founder-admin-runbook",
  "check:founder-tonight",
  "check:founder-auth-troubleshooting",
  "check:founder-auth-evidence",
  "check:founder-auth-admin-activation-prep",
  "check:founder-auth-admin-live-decision-packet",
  "check:founder-auth-admin-live-request-draft",
  "check:founder-auth-admin-evidence-closeout",
  "check:founder-one-pager",
  "check:investor-founder-package",
  "check:microsoft-startups",
  "check:real-status-audit",
  "check:kimi-handoff-bundle",
  "check:kimi-output-intake",
  "check:kimi-output-intake-summary",
  "check:kimi-worker-report-audit",
  "check:kimi-merge-queue",
  "check:kimi-wave-one-progress-tracker",
  "check:kimi-agent-prompts",
  "check:kimi-latest-launch-paths",
  "check:kimi-latest-intake-paths",
  "check:claude-kimi-latest-audit-bundle-paths",
  "check:kimi-latest-merge-queue-paths",
  "check:kimi-operator-dashboard",
  "check:kimi-whitepaper-dispatch-prompt",
  "check:kimi-controller-start-here",
  "check:deployment-decision-prep",
  "check:deployment-founder-env-map",
  "check:deployment-live-action-decision-packet",
  "check:deployment-founder-external-setup-closeout",
  "check:closeout-validator-count-drift",
  "check:deploy-brief",
  "check:vercel-preflight",
  "check:vercel-founder-setup-walkthrough",
  "check:vercel-env-matrix",
  "check:vercel-postdeploy",
  "check:public-beta-env-report",
  "check:public-beta-smoke-commands",
  "check:public-beta-url-smoke-evidence-intake",
  "check:public-beta-deploy-to-invite-handoff",
  "check:public-beta-invite-evidence-closeout",
  "check:public-beta-invite-approval-request-draft",
  "check:public-beta-invite-founder-send-checklist",
  "check:public-beta-invite-post-send-intake",
  "check:public-beta-first-response-triage",
  "check:public-beta-founder-reply-boundary",
  "check:public-beta-founder-reply-record-closeout",
  "check:public-beta-first-batch-support-summary",
  "check:public-beta-first-batch-founder-support-handoff",
  "check:public-beta-first-batch-founder-support-decision-intake",
  "check:public-beta-first-batch-internal-action-queue",
  "check:public-beta-first-batch-internal-action-closeout",
  "check:public-beta-first-batch-support-trend-rollup",
  "check:public-beta-first-batch-support-trend-founder-handoff",
  "check:public-beta-first-batch-support-trend-founder-decision-intake",
  "check:public-beta-first-batch-support-trend-founder-decision-closeout",
  "check:public-beta-first-batch-support-trend-internal-action-queue",
  "check:public-beta-first-batch-support-trend-internal-action-closeout",
  "check:public-beta-first-batch-support-trend-internal-action-archive",
  "check:public-beta-first-batch-support-trend-archive-index",
  "check:public-beta-first-batch-support-trend-archive-index-closeout",
  "check:public-beta-first-batch-support-trend-archive-index-handoff",
  "check:public-beta-first-batch-support-trend-archive-index-founder-decision-intake",
  "check:public-beta-first-batch-support-trend-archive-index-founder-decision-closeout",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-queue",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout-handoff",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout-handoff-closeout",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout-handoff-closeout-handoff",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout-handoff-closeout-handoff-closeout",
  "check:public-beta-first-batch-support-trend-archive-index-internal-action-closeout-handoff-closeout-handoff-closeout-handoff",
  "check:public-beta-rollback-drill",
  "check:public-beta-incident-response",
  "check:public-beta-support-queue",
  "check:public-beta-support-sla",
  "check:public-beta-known-issues",
  "check:public-beta-tester-quickstart",
  "check:public-beta-founder-dashboard",
  "check:public-beta-daily-status",
  "check:public-beta-weekly-closeout",
  "check:public-beta-metrics-snapshot",
  "check:public-beta-launch-readiness",
  "check:public-beta-tester-cohort",
  "check:public-beta-first-cohort-launch-packet",
  "check:public-beta-invite-release-decision-packet",
  "check:public-beta-invite-batches",
  "check:public-beta-session-schedule",
  "check:public-beta-session-moderator",
  "check:public-beta-session-postmortem",
  "check:public-beta-issue-escalation",
  "check:public-beta-issue-closure",
  "check:public-beta-regression-checklist",
  "check:public-beta-qa-signoff",
  "check:public-beta-launch-decision-record",
  "check:public-beta-launch-day-checklist",
  "check:public-beta-launch-status-board",
  "check:public-beta-launch-day-recap",
  "check:public-beta-next-day-followup",
  "check:public-beta-day-two-checkpoint",
  "check:public-beta-day-three-review",
  "check:public-beta-day-four-stabilization",
  "check:public-beta-day-five-monitoring",
  "check:public-beta-day-six-decision",
  "check:public-beta-day-seven-readiness",
  "check:public-beta-week-one-decision",
  "check:public-beta-week-two-plan",
  "check:public-beta-week-two-kickoff",
  "check:public-beta-week-two-day-one-status",
  "check:public-beta-week-two-day-two-checkpoint",
  "check:public-beta-week-two-day-three-review",
  "check:public-beta-week-two-day-four-stabilization",
  "check:public-beta-week-two-day-five-monitoring",
  "check:public-beta-week-two-day-six-decision",
  "check:public-beta-week-two-day-seven-readiness",
  "check:public-beta-week-two-closeout",
  "check:public-beta-week-three-plan",
  "check:public-beta-week-three-kickoff",
  "check:public-beta-week-three-day-one-status",
  "check:public-beta-week-three-day-two-checkpoint",
  "check:public-beta-week-three-day-three-review",
  "check:public-beta-week-three-day-four-stabilization",
  "check:public-beta-week-three-day-five-monitoring",
  "check:public-beta-week-three-day-six-decision",
  "check:public-beta-week-three-day-seven-readiness",
  "check:public-beta-week-three-closeout",
  "check:public-beta-week-four-plan",
  "check:public-beta-week-four-kickoff",
  "check:public-beta-launch-message",
  "check:public-beta-tester-faq",
  "check:public-beta-consent-ack",
  "check:public-beta-privacy-notice",
  "check:public-beta-consent-withdrawal",
  "check:public-beta-reinvite-checklist",
  "check:public-beta-data-deletion",
  "check:public-beta-data-export",
  "check:public-beta-data-correction",
  "check:public-beta-use-restriction",
  "check:public-beta-terms-summary",
  "check:public-beta-offboarding",
  "check:public-beta-handoff",
  "check:public-launch-runbook",
  "check:ci-workflow",
  "check:env-example",
  "check:claude-code-prompt",
  "check:public-beta-week-four-day-one-status",
  "check:public-beta-week-four-day-two-checkpoint",
  "check:public-beta-week-four-day-three-review",
  "check:public-beta-week-four-day-four-stabilization",
  "check:public-beta-week-four-day-five-monitoring",
  "check:public-beta-week-four-day-six-decision",
  "check:public-beta-week-four-day-seven-readiness",
  "check:whitepaper-v1-2-restructure",
  "check:whitepaper-v1-2-founder-review",
  "check:whitepaper-v1-2-edit-plan",
  "check:whitepaper-v1-2-source-map",
  "check:whitepaper-v1-2-publish-gate",
  "check:whitepaper-v1-2-approval-record",
  "check:whitepaper-v1-2-founder-decision-packet",
  "check:whitepaper-v1-2-public-excerpt-guard",
  "check:whitepaper-v1-2-terms-glossary",
  "check:whitepaper-v1-2-claim-review",
  "check:whitepaper-v1-2-public-edit-queue",
  "check:whitepaper-v1-2-public-wording-package",
  "check:whitepaper-v1-2-public-website-update-packet",
  "check:whitepaper-v1-2-founder-approval-brief",
  "check:whitepaper-v1-2-redline-preview",
  "check:whitepaper-v1-2-section-replacement-preview",
  "check:whitepaper-v1-2-founder-review-worksheet",
  "check:whitepaper-v1-2-founder-response-intake",
  "check:whitepaper-v1-2-review-change-log",
  "check:whitepaper-v1-2-publication-dry-run",
  "check:whitepaper-v1-2-publication-rollback-plan",
  "check:whitepaper-v1-2-publication-evidence-log",
  "check:whitepaper-v1-2-publication-go-no-go",
  "check:whitepaper-v1-2-publication-correction-notice",
  "check:whitepaper-v1-2-publication-version-history",
  "check:whitepaper-v1-2-publication-distribution-log",
  "check:whitepaper-v1-2-publication-follow-up-queue",
  "check:whitepaper-v1-2-publication-response-boundary",
  "check:whitepaper-v1-2-publication-response-approval-stamp",
  "check:whitepaper-v1-2-smart-contract-architecture",
  "check:whitepaper-v1-2-contract-backed-loan-addendum",
  "check:whitepaper-v1-2-contract-backed-loan-flow",
  "check:whitepaper-v1-2-contract-backed-loan-founder-review",
  "check:whitepaper-v1-2-contract-backed-loan-review-questions",
  "check:whitepaper-v1-2-contract-backed-loan-public-wording-options",
  "check:whitepaper-v1-2-contract-backed-loan-wording-selection-record",
  "check:whitepaper-v1-2-contract-backed-loan-approval-routing",
  "check:whitepaper-v1-2-contract-backed-loan-public-use-gate",
  "check:whitepaper-v1-2-contract-backed-loan-exact-sentence-register",
  "check:whitepaper-v1-2-contract-backed-loan-placement-map",
  "check:whitepaper-v1-2-contract-backed-loan-public-excerpt-review-packet",
  "check:whitepaper-v1-2-contract-backed-loan-founder-reading-order",
  "check:whitepaper-v1-2-contract-backed-loan-founder-response-template",
  "check:whitepaper-v1-2-contract-backed-loan-founder-response-triage-log",
  "check:whitepaper-v1-2-contract-backed-loan-founder-review-index",
  "check:whitepaper-v1-2-contract-backed-loan-founder-packet-status",
  "check:whitepaper-v1-2-contract-backed-loan-founder-review-closeout",
  "check:whitepaper-v1-2-contract-backed-loan-founder-decision-summary",
  "check:whitepaper-v1-2-contract-backed-loan-legal-provider-handoff",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-legal-provider-review",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-reason-code-taxonomy",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-notice-template-boundary",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-approval-evidence-template",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-review-response-intake-log",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-review-response-routing",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-review-response-action-plan",
  "check:whitepaper-v1-2-contract-backed-loan-adverse-action-review-response-closeout",
  "check:whitepaper-v1-2-contract-backed-loan-finance-provider-handoff",
  "check:whitepaper-v1-2-contract-backed-loan-technical-handoff",
  "check:whitepaper-v1-2-contract-backed-loan-implementation-readiness-matrix",
  "check:whitepaper-v1-2-contract-backed-loan-implementation-blocker-register",
  "check:whitepaper-v1-2-contract-backed-loan-implementation-approval-index",
  "check:whitepaper-v1-2-contract-backed-loan-approval-evidence-template",
  "check:whitepaper-v1-2-contract-backed-loan-technical-requirements",
  "check:whitepaper-v1-2-contract-backed-loan-repayment-failure-state-matrix",
  "check:whitepaper-v1-2-smart-contract-module-split-anti-backdoor",
  "check:whitepaper-v1-2-legal-provider-review-prep",
  "check:whitepaper-v1-2-legal-provider-review-executive-brief",
  "check:whitepaper-v1-2-legal-provider-review-founder-send-checklist",
  "check:whitepaper-v1-2-legal-provider-review-response-intake-log",
  "check:whitepaper-v1-2-legal-provider-review-response-routing",
  "check:whitepaper-v1-2-full-audit-kimi-plan",
  "check:whitepaper-v1-2-public-draft",
  "check:whitepaper-v1-2-public-draft-founder-review-packet",
  "check:whitepaper-v1-2-public-draft-founder-response-intake",
  "check:whitepaper-v1-2-public-draft-revision-plan",
  "check:whitepaper-v1-2-public-draft-revision-checklist",
  "check:whitepaper-v1-2-public-draft-revision-worker-packet",
  "check:whitepaper-v1-2-public-draft-revision-worker-prompts",
  "check:whitepaper-v1-2-public-draft-revision-worker-prompt-paths",
  "check:whitepaper-v1-2-public-draft-revision-dispatch-prompt",
  "check:whitepaper-v1-2-public-draft-revision-controller-start-here",
  "check:whitepaper-v1-2-public-draft-revision-output-intake",
  "check:whitepaper-v1-2-public-draft-revision-integration-ledger",
  "check:whitepaper-v1-2-public-draft-revision-founder-closeout"
];

function fail(message) {
  console.error(`[run-checks] ${message}`);
  process.exit(1);
}

if (checkScripts.length === 0) {
  fail('Missing check script entries in package.json');
}
if (packageJson.name !== expectedPackageName) {
  fail('Check runner must run from construction-ai workspace');
}

const packageCheckScripts = Object.keys(packageJson.scripts || {})
  .filter((scriptName) => scriptName.startsWith('check:'));
const duplicateCheckScripts = checkScripts.filter((scriptName, index) => checkScripts.indexOf(scriptName) !== index);
const missingFromRunner = packageCheckScripts.filter((scriptName) => !checkScripts.includes(scriptName));
const missingFromPackage = checkScripts.filter((scriptName) => !packageJson.scripts?.[scriptName]);
const allowedCheckCommandPattern = /^node scripts\/[a-z0-9-]+\.mjs$/i;
const scriptsRoot = resolve('scripts');
const startedAt = Date.now();
const startedAtIso = new Date(startedAt).toISOString();

if (duplicateCheckScripts.length > 0) {
  fail(`Duplicate check script entries: ${duplicateCheckScripts.join(', ')}`);
}
if (missingFromRunner.length > 0) {
  fail(`Missing check scripts from runner: ${missingFromRunner.join(', ')}`);
}
if (missingFromPackage.length > 0) {
  fail(`Missing check script entries in package.json: ${missingFromPackage.join(', ')}`);
}

const npmBin = process.platform === 'win32' ? 'npm.cmd' : 'npm';

for (const scriptName of checkScripts) {
  const scriptCommand = packageJson.scripts?.[scriptName];
  if (!allowedCheckCommandPattern.test(scriptCommand)) {
    fail(`Unsupported check script command for ${scriptName}`);
  }

  const validatorRelativePath = scriptCommand.slice('node '.length);
  const scriptPath = resolve(validatorRelativePath);
  if (!scriptPath.startsWith(`${scriptsRoot}${sep}`)) {
    fail(`Validator path must stay inside scripts directory for ${scriptName}: ${scriptPath}`);
  }
  if (!existsSync(scriptPath)) {
    fail(`Missing validator file for ${scriptName}: ${scriptPath}`);
  }

  console.log(`\n[run-checks] ${scriptName}`);
  const result = spawnSync(process.execPath, scriptCommand.slice('node '.length).split(' '), {
    cwd: resolve('.'),
    stdio: 'inherit',
    shell: false,
  });

  if (result.error) {
    fail(result.error.message);
  }

  if (result.status !== 0) {
    console.error(JSON.stringify({
      status: 'failed',
      failed_check_script: scriptName,
      checks_completed_before_failure: checkScripts.indexOf(scriptName),
      started_at_iso: startedAtIso,
      failed_at_iso: new Date().toISOString(),
      duration_ms_before_failure: Date.now() - startedAt,
    }, null, 2));
    process.exit(result.status ?? 1);
  }
}

const finishedAt = Date.now();
console.log(JSON.stringify({
  status: 'passed',
  package_name_checked: packageJson.name,
  expected_package_name_checked: expectedPackageName,
  package_json_path_checked: packagePath,
  check_runner_workspace: resolve('.'),
  node_version_checked: process.version,
  platform_checked: process.platform,
  npm_binary_checked: npmBin,
  started_at_iso: startedAtIso,
  finished_at_iso: new Date(finishedAt).toISOString(),
  duration_ms_checked: finishedAt - startedAt,
  duplicate_check_scripts_checked: duplicateCheckScripts.length,
  package_check_scripts_total_checked: packageCheckScripts.length,
  missing_from_runner_checked: missingFromRunner.length,
  missing_from_package_checked: missingFromPackage.length,
  validator_root_checked: scriptsRoot,
  check_command_pattern_checked: allowedCheckCommandPattern.source,
  checks_run: checkScripts.length,
  first_check_script: checkScripts[0],
  last_check_script: checkScripts[checkScripts.length - 1],
}, null, 2));
